#!/bin/bash
# verify.sh - runs the declared verify_gate for plan "add-structured-next-action-hints-to-unbrowse-mcp".
# Generated by meta-harness build.py.
#
# Two phases:
#   1. Run verify_command (single-binary check).
#   2. If references/criteria.md declares lanes:, run each bench_command and
#      append raw rows to ledgers/lanes.jsonl. Agent judges.
#
# Edit state file frontmatter or references/criteria.md to change behavior.
set -uo pipefail
# scripts/verify.sh -> ../../.. is the project root
cd "$(dirname "$0")/../../.."
export PLAN=add-structured-next-action-hints-to-unbrowse-mcp
# scripts/verify.sh -> ../ is the plan scaffold root
export SCAFFOLD="$(cd "$(dirname "$0")/.." && pwd)"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "[verify:$PLAN] gate: os-control e2e outcome (bench preflight)"
echo "[verify:$PLAN] command:"
echo "  { test -f .bench-gate/run.sh && bash .bench-gate/run.sh || echo 'no bench-gate yet'; }; { echo '[validation_channel=os-control] bench preflight done. Declare the real e2e outcome check as verify_comma"
set +e
{ test -f .bench-gate/run.sh && bash .bench-gate/run.sh || echo 'no bench-gate yet'; }; { echo '[validation_channel=os-control] bench preflight done. Declare the real e2e outcome check as verify_command in the state file: screencapture -x -R<x,y,w,h> /tmp/$PLAN-v.png + an image/vision diff, OR an osascript UI assertion, OR for an API surface set validation_channel: http-curl and a curl matrix against the deployed endpoint. Bench alone is not an e2e gate.'; false; }
VERIFY_RC=$?
set -e

# Phase 2: lane evidence (only if references/criteria.md declares lanes:)
CRITERIA="$SCAFFOLD/references/criteria.md"
if [[ -f "$CRITERIA" ]] && grep -q "^lanes:" "$CRITERIA"; then
  echo "[verify:$PLAN] lanes declared - collecting raw evidence per lane"
  python3 - <<'PYLANE'
import re, json, os, subprocess
from datetime import datetime
scaffold = os.environ["SCAFFOLD"]
plan = os.environ["PLAN"]
crit_path = os.path.join(scaffold, "references", "criteria.md")
ledger = os.path.join(scaffold, "ledgers", "lanes.jsonl")
text = open(crit_path).read()
m = re.search(r"```yaml\s*(.*?)```", text, re.S)
block = m.group(1) if m else text
lanes = []
cur = None
def _unquote(raw):
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ('"', "'"):
        return raw[1:-1]
    return raw
for line in block.splitlines():
    s = line.rstrip()
    if re.match(r"^\s*-\s+id:", s):
        if cur:
            lanes.append(cur)
        cur = {"id": _unquote(s.split("id:", 1)[1])}
    elif cur and re.match(r"^\s+(question|bench_command|source_id):", s):
        k = s.strip().split(":", 1)[0].strip()
        v = _unquote(s.split(":", 1)[1])
        cur[k] = v
if cur:
    lanes.append(cur)
ts = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
for lane in lanes:
    cmd = lane.get("bench_command", "")
    if not cmd:
        row = {"lane": lane.get("id"), "ts": ts, "plan": plan,
               "exit_code": None, "output_tail": "no bench_command", "skipped": True}
    else:
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        tail = (r.stdout + r.stderr).strip()[-400:]
        row = {"lane": lane.get("id"), "ts": ts, "plan": plan,
               "question": lane.get("question", ""),
               "source_id": lane.get("source_id", ""),
               "exit_code": r.returncode, "output_tail": tail}
    with open(ledger, "a") as fh:
        fh.write(json.dumps(row) + "\n")
    print(f"  [{lane.get('id')}] exit={row.get('exit_code')}")
PYLANE
fi
exit $VERIFY_RC
