// UNBROWSE_GATE_STOP_ON_FAIL=1 makes the collector force conc=1 and exit
// at the first probe whose artifact fails the lane-aware structural-pass
// predicate. The agent reads .stop-marker, ships a fix, re-runs (the
// resume-skip rule pulls the still-broken probe back into the run).
//
// Structural test: the source file at scripts/mcp-gate-parallel-collect.ts
// must declare:
//   - the STOP_ON_FAIL flag (env-driven)
//   - the structuralPassPredicate function
//   - the .stop-marker write path inside the worker pool
//   - process.exit(2) on the stopped branch (so a wrapping shell can
//     branch on the exit code instead of grepping logs)
//
// This is a structural pin, not a runtime test. The smoke run on three real
// probes was captured separately at .bench-gate/smoke-stop-on-fail-*; the
// artifact below would be regenerated by a real-runtime test that runs the
// collector against a tiny corpus, which takes ~30s and is gated outside
// this fast suite.

import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..");
const COLLECTOR_SRC = readFileSync(join(REPO_ROOT, "scripts/mcp-gate-parallel-collect.ts"), "utf8");

describe("bench-gate collector stop-on-fail mode", () => {
  it("declares STOP_ON_FAIL env flag and forces conc=1 when set", () => {
    expect(COLLECTOR_SRC).toMatch(/UNBROWSE_GATE_STOP_ON_FAIL/);
    expect(COLLECTOR_SRC).toMatch(/const STOP_ON_FAIL =/);
    expect(COLLECTOR_SRC).toMatch(/const CONC = STOP_ON_FAIL \? 1 : CONC_ENV/);
  });

  it("declares structuralPassPredicate covering auth-gated, hostile, and non-excluded lanes", () => {
    expect(COLLECTOR_SRC).toMatch(/function structuralPassPredicate/);
    expect(COLLECTOR_SRC).toMatch(/lane === "auth-gated" \|\| lane === "auth-cookies"/);
    expect(COLLECTOR_SRC).toMatch(/lane === "hostile"/);
    expect(COLLECTOR_SRC).toMatch(/non-excluded lane/);
    expect(COLLECTOR_SRC).toMatch(/resolve_hard_handoff/);
    expect(COLLECTOR_SRC).toMatch(/perimeterx\|datadome\|akamai/);
  });

  it("worker writes .stop-marker on structural fail and the script exits 2", () => {
    expect(COLLECTOR_SRC).toMatch(/\.stop-marker/);
    expect(COLLECTOR_SRC).toMatch(/structural_fail_reason/);
    expect(COLLECTOR_SRC).toMatch(/process\.exit\(2\)/);
  });

  it("resume-skip still applies so the stopped probe is re-run while completed probes are not", () => {
    expect(COLLECTOR_SRC).toMatch(/existsSync\(join\(dir, "execute\.meta\.json"\)\)/);
    expect(COLLECTOR_SRC).toMatch(/SKIP \(already collected\)/);
  });
});
