/**
 * Signed-declare round-trip — proves a real ed25519 keypair generated by
 * Web Crypto can sign a canonical declare body, the server verifier accepts
 * the signature, and tampering with any signed field (plan/action/parent/
 * agent/wallet/ts) causes rejection.
 */
import { describe, expect, test } from "bun:test";
import { Hono } from "hono";
import { contractRoutes } from "../src/routes/contract";
import {
  canonicalizeDeclareBody,
  verifyDeclareSignature,
  type CanonicalDeclareBody,
} from "../src/services/declare-signature";

function mountApp() {
  const app = new Hono();
  app.route("/v1", contractRoutes);
  return app;
}

function bytesToHex(b: ArrayBuffer | Uint8Array): string {
  const u8 = b instanceof Uint8Array ? b : new Uint8Array(b);
  return Array.from(u8).map((x) => x.toString(16).padStart(2, "0")).join("");
}

async function genKeypair(): Promise<{ pubHex: string; privKey: CryptoKey }> {
  const kp = await crypto.subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]) as CryptoKeyPair;
  const pubRaw = await crypto.subtle.exportKey("raw", kp.publicKey);
  return { pubHex: bytesToHex(pubRaw), privKey: kp.privateKey };
}

async function signCanonical(body: CanonicalDeclareBody, privKey: CryptoKey): Promise<string> {
  const canon = canonicalizeDeclareBody(body);
  const sig = await crypto.subtle.sign({ name: "Ed25519" }, privKey, new TextEncoder().encode(canon));
  return bytesToHex(sig);
}

describe("verifyDeclareSignature — unit", () => {
  test("valid signature verifies true", async () => {
    const { pubHex, privKey } = await genKeypair();
    const body: CanonicalDeclareBody = {
      plan: "real plan",
      action: "neuron",
      parent_id: null,
      agent: "alice",
      wallet_identity: pubHex,
      ts: "2026-05-25T20:00:00Z",
    };
    const sig = await signCanonical(body, privKey);
    expect(await verifyDeclareSignature(body, sig)).toBe(true);
  });

  test("tampered plan field rejects", async () => {
    const { pubHex, privKey } = await genKeypair();
    const body: CanonicalDeclareBody = {
      plan: "original plan",
      action: "neuron",
      parent_id: null,
      agent: "alice",
      wallet_identity: pubHex,
      ts: "2026-05-25T20:00:00Z",
    };
    const sig = await signCanonical(body, privKey);
    const tampered = { ...body, plan: "evil plan" };
    expect(await verifyDeclareSignature(tampered, sig)).toBe(false);
  });

  test("wrong pubkey rejects (signature was over a different key)", async () => {
    const { privKey: aliceKey } = await genKeypair();
    const { pubHex: bobPub } = await genKeypair();
    const body: CanonicalDeclareBody = {
      plan: "plan",
      action: "neuron",
      parent_id: null,
      agent: "alice",
      wallet_identity: bobPub,
      ts: "2026-05-25T20:00:00Z",
    };
    // Alice signs but claims Bob's pubkey — must reject
    const sig = await signCanonical(body, aliceKey);
    expect(await verifyDeclareSignature(body, sig)).toBe(false);
  });

  test("malformed signature returns false (not throws)", async () => {
    const { pubHex } = await genKeypair();
    const body: CanonicalDeclareBody = {
      plan: "p", action: "neuron", parent_id: null, agent: "a", wallet_identity: pubHex, ts: "t",
    };
    expect(await verifyDeclareSignature(body, "not-hex")).toBe(false);
    expect(await verifyDeclareSignature(body, "deadbeef")).toBe(false);
  });
});

describe("/v1/contract/declare — signed write gate (#33)", () => {
  async function postJson(app: Hono, path: string, body: unknown) {
    const res = await app.fetch(
      new Request(`http://test.local${path}`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(body),
      }),
    );
    return { status: res.status, json: await res.json() };
  }

  test("anonymous declare (no wallet, no sig) still works — coerced to anonymous+public", async () => {
    const app = mountApp();
    const { status, json } = await postJson(app, "/v1/contract/declare", {
      plan: "anon write",
      action: "neuron",
      agent: "claim-i-am-someone-else",
    });
    expect(status).toBe(200);
    const body = json as { row: { agent: string; visibility: string } };
    // Agent coerced; visibility auto-public
    expect(body.row.agent).toBe("anonymous");
    expect(body.row.visibility).toBe("public");
  });

  test("wallet_identity without signature rejects 400", async () => {
    const app = mountApp();
    const { status, json } = await postJson(app, "/v1/contract/declare", {
      plan: "x", action: "neuron", wallet_identity: "deadbeef",
    });
    expect(status).toBe(400);
    expect((json as { error: string }).error).toContain("declare_signature required");
  });

  test("signature without wallet_identity rejects 400", async () => {
    const app = mountApp();
    const { status, json } = await postJson(app, "/v1/contract/declare", {
      plan: "x", action: "neuron", declare_signature: "deadbeef",
    });
    expect(status).toBe(400);
    expect((json as { error: string }).error).toContain("meaningless");
  });

  test("invalid signature rejects 401", async () => {
    const app = mountApp();
    const { pubHex } = await genKeypair();
    const { status, json } = await postJson(app, "/v1/contract/declare", {
      plan: "x",
      action: "neuron",
      wallet_identity: pubHex,
      declare_signature: "00".repeat(64), // 64 zero bytes — not a valid sig
      ts: "2026-05-25T20:00:00Z",
    });
    expect(status).toBe(401);
    expect((json as { error: string }).error).toContain("invalid");
  });

  test("valid signature accepts + persists wallet_identity", async () => {
    const app = mountApp();
    const { pubHex, privKey } = await genKeypair();
    const ts = "2026-05-25T20:00:00Z";
    const body: CanonicalDeclareBody = {
      plan: "real-signed-write",
      action: "neuron",
      parent_id: null,
      agent: "alice",
      wallet_identity: pubHex,
      ts,
    };
    const sig = await signCanonical(body, privKey);
    const { status, json } = await postJson(app, "/v1/contract/declare", {
      plan: body.plan,
      action: body.action,
      agent: body.agent,
      wallet_identity: pubHex,
      declare_signature: sig,
      ts,
    });
    expect(status).toBe(200);
    const row = (json as { row: { agent: string; wallet_identity: string; ts: string; visibility: string } }).row;
    expect(row.agent).toBe("alice"); // signed identity respected
    expect(row.wallet_identity).toBe(pubHex);
    expect(row.ts).toBe(ts); // server didn't restamp
    expect(row.visibility).toBe("lineage"); // wallet-bound → default lineage
  });
});
