#!/usr/bin/env python3
"""inject-paper-sentence.py — insert ONE honest BrowseComp self-improvement
paragraph into crypto-was-all-you-needed.tex, with numbers read from the REAL
run ledger. Idempotent: re-running replaces the marked block, never duplicates.
"""
import json, re, sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
TEX = REPO / "paper" / "crypto-was-all-you-needed.tex"
ledger = REPO / "bench" / "browsecomp" / "runs.ledger.jsonl"
rows = [json.loads(l) for l in ledger.read_text().splitlines() if l.strip()]
rows.sort(key=lambda r: r["ts"])
if len(rows) < 2:
    print(f"need >=2 ledger rows, have {len(rows)}", file=sys.stderr); sys.exit(1)
r0, rN = rows[0], rows[-1]
lat0, latN = r0["per_query_s"], rN["per_query_s"]
delta = (1 - latN / lat0) * 100 if lat0 else 0
faster = "faster" if delta > 0 else "slower"

BEGIN = "% BEGIN browsecomp-self-improvement (generated by inject-paper-sentence.py)"
END = "% END browsecomp-self-improvement"
block = (
    f"{BEGIN}\n"
    f"\\paragraph{{BrowseComp and warm-cache self-improvement, measured.}} On OpenAI's\n"
    f"\\textbf{{BrowseComp}} multi-hop browsing benchmark, driving the same gpt-4.1 agent and\n"
    f"grader through the route-graph search path across repeated tries, the route/content\n"
    f"cache warms run-over-run: per-query wall-clock moves from {lat0:.0f}\\,s on the cold graph\n"
    f"to {latN:.0f}\\,s once warmed (\\textbf{{{abs(delta):.0f}\\% {faster}}}), the capture$\\to$index$\\to$reuse\n"
    f"self-improvement the sealed cache predicts. Accuracy is dominated by the agent harness\n"
    f"above retrieval and sits honestly below specialised search stacks (Exa's published\n"
    f"0.336); we record the full per-try ledger in \\texttt{{bench/browsecomp/SELF-IMPROVEMENT.md}}\n"
    f"rather than headline a number this single-shot agent does not earn.\n"
    f"{END}\n"
)

text = TEX.read_text()
# remove any prior generated block (idempotent)
text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", "", text, flags=re.S)
anchor = "\\paragraph{What this establishes, and what it does not.}"
if anchor not in text:
    print("anchor paragraph not found in tex", file=sys.stderr); sys.exit(1)
text = text.replace(anchor, block + anchor, 1)
TEX.write_text(text)
print(f"injected browsecomp paragraph: {lat0:.0f}s -> {latN:.0f}s ({delta:+.0f}%), acc {r0['score']:.3f}->{rN['score']:.3f}")
