export const BUILD_RELEASE_VERSION = "8.1.1";
export const BUILD_GIT_SHA = "23292202470d";
export const BUILD_CODE_HASH = "5d9ebf619c61";
export const BUILD_RELEASE_MANIFEST_BASE64 = "eyJzY2hlbWFfdmVyc2lvbiI6MSwicmVsZWFzZV92ZXJzaW9uIjoiOC4xLjEiLCJnaXRfc2hhIjoiMjMyOTIyMDI0NzBkIiwiY29kZV9oYXNoIjoiNWQ5ZWJmNjE5YzYxIiwidHJhY2VfdmVyc2lvbiI6IjVkOWViZjYxOWM2MUAyMzI5MjIwMjQ3MGQiLCJpc3N1ZWRfYXQiOiIyMDI2LTA2LTA1VDAyOjMyOjA5LjcwNloifQ";
export const BUILD_RELEASE_MANIFEST_SIGNATURE = "5Qm0Cfq61CnwxcwD7VMpIaNx370ksYKRaPchiZKDKBA";
export const BUILD_DEFAULT_BACKEND_URL = "https://beta-api.unbrowse.ai";
export const BUILD_DEFAULT_PROFILE = "";
