export const BUILD_RELEASE_VERSION = "8.3.1";
export const BUILD_GIT_SHA = "4fb74e5e4808";
export const BUILD_CODE_HASH = "5d9ebf619c61";
export const BUILD_RELEASE_MANIFEST_BASE64 = "eyJzY2hlbWFfdmVyc2lvbiI6MSwicmVsZWFzZV92ZXJzaW9uIjoiOC4zLjEiLCJnaXRfc2hhIjoiNGZiNzRlNWU0ODA4IiwiY29kZV9oYXNoIjoiNWQ5ZWJmNjE5YzYxIiwidHJhY2VfdmVyc2lvbiI6IjVkOWViZjYxOWM2MUA0ZmI3NGU1ZTQ4MDgiLCJpc3N1ZWRfYXQiOiIyMDI2LTA2LTEzVDAwOjA1OjQ1LjM5NloifQ";
export const BUILD_RELEASE_MANIFEST_SIGNATURE = "FfLpwo-kH3_gvxZiTZJugYPgNnbsaFHlg_SEgLAV294";
export const BUILD_DEFAULT_BACKEND_URL = "https://beta-api.unbrowse.ai";
export const BUILD_DEFAULT_PROFILE = "";
