export const BUILD_RELEASE_VERSION = "6.17.0-preview.6";
export const BUILD_GIT_SHA = "ed79f04f76e5";
export const BUILD_CODE_HASH = "5d9ebf619c61";
export const BUILD_RELEASE_MANIFEST_BASE64 = "eyJzY2hlbWFfdmVyc2lvbiI6MSwicmVsZWFzZV92ZXJzaW9uIjoiNi4xNy4wLXByZXZpZXcuNiIsImdpdF9zaGEiOiJlZDc5ZjA0Zjc2ZTUiLCJjb2RlX2hhc2giOiI1ZDllYmY2MTljNjEiLCJ0cmFjZV92ZXJzaW9uIjoiNWQ5ZWJmNjE5YzYxQGVkNzlmMDRmNzZlNSIsImlzc3VlZF9hdCI6IjIwMjYtMDUtMjJUMDk6MTY6NDAuNjI1WiJ9";
export const BUILD_RELEASE_MANIFEST_SIGNATURE = "WWgh-W9BB0m16asfbhGPYUF42T7cmXsM3hlR60TZniM";
export const BUILD_DEFAULT_BACKEND_URL = "https://beta-api.unbrowse.ai";
export const BUILD_DEFAULT_PROFILE = "";
